### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by ro6** [funcool/buddy#22]
Looks like the documentation at https://niwibe.github.io/buddy/latest/ is out of date with the latest in the repo. Specifically, the lines:
```
;; Use them like plain secret password with hmac algorithms for sign
(def signed-data (sign "mystring" ec-privkey {:alg :ec256}))

;; And unsign
(def unsigned-data (unsign signed-data ec-pubkey {:alg :ec256}))
```
Should have `:es256` instead of `:ec256`

**Comment by niwibe** [comment]
This should be fixed in the last version.
