### ISSUE TITLE
Link to Buddy submodules in README

### ISSUE THREAD

**Issue by deadghost** [funcool/buddy#29]
I didn't even notice the submodules were in separate repos.

**Comment by niwibe** [comment]
Is explained here: https://github.com/funcool/buddy#backward-compatibility and here: https://github.com/funcool/buddy#modules-summary

**Comment by deadghost** [comment]
Some html links to the repo urls would be nice in addition.

**Comment by niwibe** [comment]
Yeah, you are right, I will add it ;)
