### ISSUE TITLE
Link to latest docs broken

### ISSUE THREAD

**Issue by ulsa** [funcool/buddy#32]
https://funcool.github.io/buddy/latest/

**Comment by niwinz** [comment]
Yes, because now the main information about this meta package is found on README.adoc. Where you are found this link?

**Comment by ulsa** [comment]
It's in many places, eg the [buddy front page](http://funcool.github.io/buddy-auth/), the [buddy readme](https://github.com/funcool/buddy), the [Luminus auth page](http://www.luminusweb.net/docs/routes.md#restricting_access_based_on_uri).

**Comment by niwinz** [comment]
Ok, the buddy front page is outdated. Currently everything is located in the readme.

In buddy readme I can't find any broken link.
And about luminus page, I'll write to its maintainer for fix it.

Thanks

**Comment by ulsa** [comment]
Sorry, the buddy readme doesn't have it, but the others do.

**Comment by niwinz** [comment]
The buddy-front page is deleted so should not be an issue now. The main front page of the buddy meta package is the github readme.
Also I have written to luminus maintainer for fix the luminus links.

Thanks.

**Comment by niwinz** [comment]
Seems that is already fixed in luminus page.
