### ISSUE TITLE
Exception java.io.FileNotFoundException: Could not locate cats/monad/exception__init.class

### ISSUE THREAD

**Issue by johnboy14** [funcool/buddy#33]
I get the following error with 0.6.1 release of the library.  I don't experience the same issue with the previous version 0.6.0.

Caused by: java.io.FileNotFoundException: Could not locate cats/monad/exception__init.class or cats/monad/exception.clj on classpath:
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at buddy.sign.jws$eval20192$loading__4958__auto____20193.invoke(jws.clj:20)
	at buddy.sign.jws$eval20192.invoke(jws.clj:20)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 98 more
Subprocess failed

**Comment by niwinz** [comment]
Please, execute the `lein deps :tree` and paste the result. Seems to be a dependency conflict.

**Comment by johnboy14** [comment]
I had a look and the only version of this namespace on the classpath is called cats.monad.exception/exception.cljc.  I know this is a new file extension supported by Clojure for use with reader conditionals.  Once I upgraded to Clojure 1.7 this exception goes away.  Is it safe to say this version doesn't support clojure 1.6?

[lein-ring "0.8.12"] -> [org.clojure/clojure "1.2.1"]
 overrides
[lein-ring "0.8.12"] -> [leinjacker "0.4.1"] -> [org.clojure/core.contracts "0.0.1"] -> [org.clojure/core.unify "0.5.3"] -> [org.clojure/clojure "1.4.0"]
 and
[lein-ring "0.8.12"] -> [leinjacker "0.4.1"] -> [org.clojure/core.contracts "0.0.1"] -> [org.clojure/clojure "1.4.0"]
 and
[lein-ring "0.8.12"] -> [org.clojure/data.xml "0.0.6"] -> [org.clojure/clojure "1.3.0"]

Consider using these exclusions:
[lein-ring "0.8.12" :exclusions [org.clojure/clojure]]
[lein-ring "0.8.12" :exclusions [org.clojure/clojure]]
[lein-ring "0.8.12" :exclusions [org.clojure/clojure]]

Possibly confusing dependencies found:
[cider/cider-nrepl "0.8.1"] -> [org.clojure/java.classpath "0.2.0" :exclusions [org.clojure/clojure]]
 overrides
[ring/ring-devel "1.3.1"] -> [ns-tracker "0.2.2"] -> [org.clojure/java.classpath "0.2.2"]

Consider using these exclusions:
[ring/ring-devel "1.3.1" :exclusions [org.clojure/java.classpath]]

[cider/cider-nrepl "0.8.1"] -> [org.clojure/tools.namespace "0.2.5" :exclusions [org.clojure/clojure]]
 overrides
[midje "1.7.0"] -> [org.clojure/tools.namespace "0.2.7"]

Consider using these exclusions:
[midje "1.7.0" :exclusions [org.clojure/tools.namespace]]

[compojure "1.1.6"] -> [org.clojure/tools.macro "0.1.0"]
 overrides
[midje "1.7.0"] -> [org.clojure/tools.macro "0.1.5"]

Consider using these exclusions:
[midje "1.7.0" :exclusions [org.clojure/tools.macro]]

[compojure "1.1.6"] -> [clout "1.1.0"]
 overrides
[buddy "0.6.1"] -> [buddy/buddy-auth "0.6.1"] -> [clout "2.1.2"]

Consider using these exclusions:
[buddy "0.6.1" :exclusions [clout]]

[compojure "1.1.6"] -> [ring/ring-core "1.2.1"]
 overrides
[ring/ring-devel "1.3.1"] -> [ring/ring-core "1.3.1"]
 and
[ring-cors "0.1.7"] -> [ring/ring-core "1.3.2"]
 and
[ring/ring-json "0.3.1"] -> [ring/ring-core "1.2.2"]

Consider using these exclusions:
[ring/ring-devel "1.3.1" :exclusions [ring/ring-core]]
[ring-cors "0.1.7" :exclusions [ring/ring-core]]
[ring/ring-json "0.3.1" :exclusions [ring/ring-core]]

[liberator "0.13"] -> [org.clojure/data.json "0.2.1"]
 overrides
[com.taoensso/carmine "2.11.1"] -> [org.clojure/data.json "0.2.6"]

Consider using these exclusions:
[com.taoensso/carmine "2.11.1" :exclusions [org.clojure/data.json]]

[midje "1.7.0"] -> [clj-time "0.9.0" :exclusions [org.clojure/clojure]]
 overrides
[buddy "0.6.1"] -> [buddy/buddy-auth "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [clj-time "0.10.0"]
 and
[buddy "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [clj-time "0.10.0"]

Consider using these exclusions:
[buddy "0.6.1" :exclusions [clj-time]]
[buddy "0.6.1" :exclusions [clj-time]]

[midje "1.7.0"] -> [slingshot "0.12.1"]
 overrides
[buddy "0.6.1"] -> [buddy/buddy-auth "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [buddy/buddy-core "0.6.0"] -> [slingshot "0.12.2"]
 and
[buddy "0.6.1"] -> [buddy/buddy-hashers "0.6.0"] -> [buddy/buddy-core "0.6.0"] -> [slingshot "0.12.2"]
 and
[buddy "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [buddy/buddy-core "0.6.0"] -> [slingshot "0.12.2"]
 and
[buddy "0.6.1"] -> [buddy/buddy-core "0.6.0"] -> [slingshot "0.12.2"]

Consider using these exclusions:
[buddy "0.6.1" :exclusions [slingshot]]
[buddy "0.6.1" :exclusions [slingshot]]
[buddy "0.6.1" :exclusions [slingshot]]
[buddy "0.6.1" :exclusions [slingshot]]

[compojure "1.1.6"] -> [ring/ring-core "1.2.1"] -> [org.clojure/tools.reader "0.7.3"]
 overrides
[buddy "0.6.1"] -> [buddy/buddy-auth "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [com.taoensso/nippy "2.9.0"] -> [com.taoensso/encore "1.32.0"] -> [org.clojure/tools.reader "0.9.2"]
 and
[buddy "0.6.1"] -> [buddy/buddy-auth "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [com.taoensso/nippy "2.9.0"] -> [org.clojure/tools.reader "0.9.2"]
 and
[buddy "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [com.taoensso/nippy "2.9.0"] -> [com.taoensso/encore "1.32.0"] -> [org.clojure/tools.reader "0.9.2"]
 and
[com.taoensso/carmine "2.11.1"] -> [com.taoensso/nippy "2.9.0"] -> [com.taoensso/encore "1.32.0"] -> [org.clojure/tools.reader "0.9.2"]
 and
[com.taoensso/carmine "2.11.1"] -> [com.taoensso/timbre "3.4.0"] -> [com.taoensso/encore "1.21.0"] -> [org.clojure/tools.reader "0.8.13"]
 and
[buddy "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [com.taoensso/nippy "2.9.0"] -> [org.clojure/tools.reader "0.9.2"]
 and
[ring/ring-devel "1.3.1"] -> [ring/ring-core "1.3.1"] -> [org.clojure/tools.reader "0.8.1"]
 and
[com.taoensso/carmine "2.11.1"] -> [com.taoensso/nippy "2.9.0"] -> [org.clojure/tools.reader "0.9.2"]
 and
[com.taoensso/carmine "2.11.1"] -> [com.taoensso/encore "1.34.0"] -> [org.clojure/tools.reader "0.9.2"]
 and
[clojurewerkz/neocons "3.1.0-beta3"] -> [clj-http "1.0.1"] -> [org.clojure/tools.reader "0.8.10" :exclusions [org.clojure/clojure]]
 and
[ring-cors "0.1.7"] -> [ring/ring-core "1.3.2"] -> [org.clojure/tools.reader "0.8.1"]
 and
[ring/ring-json "0.3.1"] -> [ring/ring-core "1.2.2"] -> [org.clojure/tools.reader "0.8.1"]

Consider using these exclusions:
[buddy "0.6.1" :exclusions [org.clojure/tools.reader]]
[buddy "0.6.1" :exclusions [org.clojure/tools.reader]]
[buddy "0.6.1" :exclusions [org.clojure/tools.reader]]
[com.taoensso/carmine "2.11.1" :exclusions [org.clojure/tools.reader]]
[com.taoensso/carmine "2.11.1" :exclusions [org.clojure/tools.reader]]
[buddy "0.6.1" :exclusions [org.clojure/tools.reader]]
[ring/ring-devel "1.3.1" :exclusions [org.clojure/tools.reader]]
[com.taoensso/carmine "2.11.1" :exclusions [org.clojure/tools.reader]]
[com.taoensso/carmine "2.11.1" :exclusions [org.clojure/tools.reader]]
[clojurewerkz/neocons "3.1.0-beta3" :exclusions [org.clojure/tools.reader]]
[ring-cors "0.1.7" :exclusions [org.clojure/tools.reader]]
[ring/ring-json "0.3.1" :exclusions [org.clojure/tools.reader]]

[midje "1.7.0"] -> [clj-time "0.9.0" :exclusions [org.clojure/clojure]] -> [joda-time "2.6"]
 overrides
[buddy "0.6.1"] -> [buddy/buddy-auth "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [clj-time "0.10.0"] -> [joda-time "2.7"]
 and
[buddy "0.6.1"] -> [buddy/buddy-sign "0.6.1"] -> [clj-time "0.10.0"] -> [joda-time "2.7"]

Consider using these exclusions:
[buddy "0.6.1" :exclusions [joda-time]]
[buddy "0.6.1" :exclusions [joda-time]]

 [buddy "0.6.1"]
   [buddy/buddy-auth "0.6.1"]
     [funcool/cuerdas "0.6.0"]
   [buddy/buddy-core "0.6.0"]
     [org.bouncycastle/bcpkix-jdk15on "1.52"]
     [org.bouncycastle/bcprov-jdk15on "1.52"]
   [buddy/buddy-hashers "0.6.0"]
     [clojurewerkz/scrypt "1.2.0"]
       [com.lambdaworks/scrypt "1.4.0"]
   [buddy/buddy-sign "0.6.1"]
     [funcool/cats "0.6.1"]
 [cheshire "5.5.0"]
   [com.fasterxml.jackson.core/jackson-core "2.5.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.5.3"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.5.3"]
   [tigris "0.1.1"]
 [cider/cider-nrepl "0.8.1"]
   [cljs-tooling "0.1.3" :exclusions [[org.clojure/clojure]]]
   [compliment "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/java.classpath "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.namespace "0.2.5" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.trace "0.7.8" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [clojurewerkz/neocons "3.1.0-beta3"]
   [clj-http "1.0.1"]
     [com.cognitect/transit-clj "0.8.259" :exclusions [[org.clojure/clojure]]]
       [com.cognitect/transit-java "0.8.269"]
         [com.fasterxml.jackson.datatype/jackson-datatype-json-org "2.3.2"]
           [com.fasterxml.jackson.core/jackson-databind "2.3.2"]
             [com.fasterxml.jackson.core/jackson-annotations "2.3.0"]
           [org.json/json "20090211"]
         [org.apache.directory.studio/org.apache.commons.codec "1.8"]
         [org.msgpack/msgpack "0.6.10"]
           [com.googlecode.json-simple/json-simple "1.1.1" :exclusions [[junit]]]
           [org.javassist/javassist "3.18.1-GA"]
       [org.clojure/test.check "0.5.9"]
     [crouton "0.1.2" :exclusions [[org.clojure/clojure]]]
       [org.jsoup/jsoup "1.7.1"]
     [org.apache.httpcomponents/httpclient "4.3.5" :exclusions [[org.clojure/clojure]]]
       [commons-logging "1.1.3"]
     [org.apache.httpcomponents/httpcore "4.3.3" :exclusions [[org.clojure/clojure]]]
     [org.apache.httpcomponents/httpmime "4.3.5" :exclusions [[org.clojure/clojure]]]
     [potemkin "0.3.8" :exclusions [[org.clojure/clojure]]]
       [clj-tuple "0.1.5"]
       [riddley "0.1.7"]
   [clojurewerkz/support "1.1.0"]
     [com.google.guava/guava "18.0"]
 [com.taoensso/carmine "2.11.1"]
   [com.taoensso/encore "1.34.0"]
   [com.taoensso/nippy "2.9.0"]
     [net.jpountz.lz4/lz4 "1.3"]
     [org.iq80.snappy/snappy "0.3"]
     [org.tukaani/xz "1.5"]
   [com.taoensso/timbre "3.4.0"]
     [io.aviso/pretty "0.1.16"]
   [commons-codec "1.10"]
   [org.apache.commons/commons-pool2 "2.4.1"]
 [compojure "1.1.6"]
   [clout "1.1.0"]
   [org.clojure/core.incubator "0.1.0"]
   [org.clojure/tools.macro "0.1.0"]
   [ring/ring-core "1.2.1"]
     [commons-fileupload "1.3"]
     [commons-io "2.4"]
     [org.clojure/tools.reader "0.7.3"]
 [environ "1.0.0"]
 [hiccup "1.0.5"]
 [liberator "0.13"]
   [org.clojure/data.csv "0.1.2"]
   [org.clojure/data.json "0.2.1"]
 [midje "1.7.0" :scope "test"]
   [clj-time "0.9.0" :exclusions [[org.clojure/clojure]]]
     [joda-time "2.6"]
   [colorize "0.1.1" :scope "test" :exclusions [[org.clojure/clojure]]]
   [dynapath "0.2.0" :scope "test"]
   [flare "0.2.8" :scope "test" :exclusions [[org.clojure/clojure]]]
     [org.clojars.brenton/google-diff-match-patch "0.1" :scope "test"]
   [ordered "1.2.0" :scope "test" :exclusions [[org.clojure/clojure]]]
   [org.clojure/core.unify "0.5.2" :scope "test" :exclusions [[org.clojure/clojure]]]
   [org.clojure/math.combinatorics "0.1.1" :scope "test"]
   [slingshot "0.12.1"]
   [swiss-arrows "1.0.0" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.7.0"]
 [org.clojure/tools.logging "0.3.1"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
 [prismatic/schema "0.4.3"]
 [ring-cors "0.1.7"]
 [ring-mock "0.1.5" :scope "test"]
   [ring/ring-codec "1.0.0"]
 [ring-server "0.3.1"]
   [ring-refresh "0.1.2"]
     [watchtower "0.1.1"]
   [ring "1.2.1"]
     [ring/ring-jetty-adapter "1.2.1"]
       [org.eclipse.jetty/jetty-server "7.6.8.v20121106"]
         [org.eclipse.jetty.orbit/javax.servlet "2.5.0.v201103041518"]
         [org.eclipse.jetty/jetty-continuation "7.6.8.v20121106"]
         [org.eclipse.jetty/jetty-http "7.6.8.v20121106"]
           [org.eclipse.jetty/jetty-io "7.6.8.v20121106"]
             [org.eclipse.jetty/jetty-util "7.6.8.v20121106"]
     [ring/ring-servlet "1.2.1"]
 [ring/ring-devel "1.3.1" :scope "test"]
   [clj-stacktrace "0.2.7" :scope "test"]
   [ns-tracker "0.2.2" :scope "test"]
 [ring/ring-json "0.3.1"]

**Comment by niwinz** [comment]
Yes, the last version of buddy only supports clojure 1.7.

**Comment by niwinz** [comment]
This is because we start using reader conditionals for share code betweeb cljs and clojure.
